---
engines:
  eslint:
    enabled: true
ratings:
  paths:
  - "src/**.js"
  - "cli/**.js"
  - "lib/aspromise/**.js"
  - "lib/base64/**.js"
  - "lib/eventemitter/**.js"
  - "lib/fetch/**.js"
  - "lib/inquire/**.js"
  - "lib/path/**.js"
  - "lib/pool/**.js"
  - "lib/utf8/**.js"
  - "**.md"
exclude_paths:
  - "dist/**"
  - "**/tests/**"
  - "cli/wrappers/**"
