language: node_js

node_js:
  - 0.12
  - 4
  - 6
  - 7

script:
  - npm test
  - npm run bench

branches:
  only:
    - master

matrix:
  include:
  - node_js: 6
    script: 
      - travis_wait npm run zuul
      - sleep 3
